### PR TITLE
Change to .io

### PR DESCRIPTION
**Pull request by hello-smile6**
You requested an impossible TLD.

### CODE REVIEW

**Comment by draeder** [comment]
This is a very old project, that I probably won't continue maintaining. Either way, .ooo is a valid domain. I own several .ooo domains including peer.ooo. For this project, I removed the GitHub pages hosting with that domain. 

I should probably set the project to private, or remove the demo portion of the readme.

**Comment by hello-smile6** [comment]
Could you get its URI updated so I can use it? I like it.

**Comment by draeder** [comment]
You should be able to run it anywhere, including locally without any server other than a working tracker server, by using index.html and index.js. The readme is old. I used to have the javascript inside of index.html, but I split it out without updating the readme. So you need both files. If you have your own tracker server, you need to update index.js to announce to it.

**Comment by draeder** [comment]
Closing since I removed Github Pages for the referenced domain & the code works without it.

**Pull request closed without merging**
